ALTER TABLE audit_contracts 
ADD COLUMN IF NOT EXISTS request_id UUID REFERENCES co2_requests(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS listing_id UUID REFERENCES co2_listings(id) ON DELETE SET NULL;
